# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ce41adc7d79b51925c680efd311a16450495fce83e36a823ab84f4d60314cf21cd55e9d1152b393f9fed10c638d80013498849c6db217645c3c537e7dde29da

test:
  secret_key_base: 0cdcfde9ac70e2c4b421bb1e396c2324312d90191e07a15f36b271d698440b5ddda1dfb0b55ff330773a1a7b52ec0c342de2cff0383ab93d1e50c13c8a26a459

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
